### ISSUE TITLE
you cms not working

### ISSUE THREAD

**Issue by zheselevko** [bigbrush/yii2-bigcms#26] opened 2015-12-15 00:39 UTC
your CMS is not running. Do not run the migration . Once everything was repaired migration but did not work because there is no one single controller module

**Comment by bigbrush** [comment] 2015-12-17 08:18
I can't reproduce that the migration is not running. Can you be a little more specific on where the installation goes wrong. There are multiple controllers (and modules) located in the vendor directory, so this is not the problem. Can you post some examples/code? Then i will look into it.

**Comment by zheselevko** [comment] 2016-01-15 20:26
the problem with migration is observed only when you put on MAMP on mac os

**Comment by zheselevko** [comment] 2016-01-15 20:27
there is 1 issue of how to make a separate page for each layout?

**Comment by bigbrush** [comment] 2016-01-18 10:50
ahh okay. I'm not on a MAC so can't reproduce it. Do you have any clue what's going on/a possible solution?

Regarding the layout, that's a missing part. I'm also in the need of it for a project so i will implement it soon.

**Comment by bigbrush** [comment] 2016-01-18 13:09
I have added the layout functionality. It will be in the next release of the BIG framework. You can use the dev version of bigbrush/yii2-big if you want to try it before.

**Closed as completed** 2016-03-21 12:49 UTC
